# Generated by Django 4.1.3 on 2022-11-11 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.PositiveIntegerField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('G', 'Gold'), ('R', 'Regular')], default='R', max_length=10)),
                ('email_id', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StoreItem',
            fields=[
                ('item_id', models.PositiveIntegerField(db_index=True, primary_key=True, serialize=False)),
                ('price', models.FloatField(verbose_name=range(0, 1000))),
                ('copies', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CartoonMovie',
            fields=[
                ('storeitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bookstore.storeitem')),
                ('title', models.CharField(max_length=20)),
                ('studio_name', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=100)),
            ],
            bases=('bookstore.storeitem',),
        ),
        migrations.CreateModel(
            name='ComicBook',
            fields=[
                ('storeitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bookstore.storeitem')),
                ('title', models.CharField(max_length=20)),
                ('published_date', models.DateField(null=True)),
            ],
            bases=('bookstore.storeitem',),
        ),
        migrations.CreateModel(
            name='GoldCustomer',
            fields=[
                ('customer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bookstore.customer')),
                ('date_joined', models.DateField()),
                ('coupon', models.CharField(max_length=10)),
            ],
            bases=('bookstore.customer',),
        ),
        migrations.CreateModel(
            name='OrderLineItem',
            fields=[
                ('line_id', models.PositiveIntegerField(db_index=True, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('store_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.storeitem')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.PositiveIntegerField(db_index=True, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('shipping_date', models.DateField(default=None)),
                ('shipping_fee', models.FloatField(default=None)),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.customer')),
                ('order_line_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.orderlineitem')),
            ],
        ),
    ]
