# Generated by Django 4.1.3 on 2022-11-11 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_fee',
            field=models.FloatField(default=None, null=True),
        ),
    ]
