# Generated by Django 4.1.3 on 2022-11-11 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_alter_order_shipping_date_alter_order_shipping_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_fee',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
