# Generated by Django 4.1.3 on 2022-11-12 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_alter_order_shipping_date_alter_order_shipping_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email_id',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='goldcustomer',
            name='date_joined',
            field=models.DateField(auto_now_add=True),
        ),
    ]
